---
plan: free
capacity: 100
local_db: sqlite3:/home/vagrant/vcap/store/echo_node/echo_node.db

mbus: nats://nats:nats@127.0.0.1:4222
base_dir: /home/vagrant/vcap/store/echo_node
index: 0
logging:
  level: debug
pid: /home/vagrant/vcap/run/echo_node.pid
node_id: echo_node_0
port: 5002
supported_versions: ["1.0"]
default_version: "1.0"

database_lock_file: /home/vagrant/vcap/store/echo_node/LOCK
disabled_file: /home/vagrant/vcap/store/echo_node/DISABLED
